### ISSUE TITLE
ＭＡＰの右下のイベント情報の見せ方

### ISSUE THREAD

**Issue by HiroAsa** [codeformatsudo/omatsuri_app#2]
・チャックボックスではないのですね？
・プルダウンして選択するのはユーザビリティ的にＮＧでしょうか？
・縦のサイズも少し微妙ですね

**Comment by 8gi** [comment]
・チャックボックスではないのですね？
　→イベント会場は一つずつ選ぶ方がわかりやすいかと思い、ラジオボタンにしてみました。
　　要検討です。
・プルダウンして選択するのはユーザビリティ的にＮＧでしょうか？
　→プルダウンにしても高さ的にはスクロールが発生してしまいます。
・縦のサイズも少し微妙ですね
　→地図の邪魔にならずに選択しやすい高さを検討したいと思います。
